[View in Colaboratory](https://colab.research.google.com/github/bell-one/tf_colab/blob/master/basic_RNN_tfipynb.ipynb)

In [0]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [0]:
# One hot encoding for each char in 'hello'# One h 
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [4]:
with tf.variable_scope('one_cell') as scope:
    # One cell RNN input_dim (4) -> output_dim (2)
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    print(cell.output_size, cell.state_size)

    x_data = np.array([[h, e, l, l, o]], dtype=np.float32) # x_data = [[[1,0,0,0]]]
    pp.pprint(x_data)
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

2 2
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)
array([[[ 0.6518432 , -0.58296347],
        [-0.7467417 , -0.22569777],
        [-0.5161284 , -0.5996152 ],
        [-0.5838013 , -0.6066532 ],
        [-0.08778545, -0.8009915 ]]], dtype=float32)


In [5]:
with tf.variable_scope('3_batches') as scope:
    # One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
    # 3 batches 'hello', 'eolll', 'lleel'
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
    outputs, _states = tf.nn.dynamic_rnn(
        cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)
array([[[-0.0821005 , -0.02892194],
        [-0.06003592, -0.15153481],
        [-0.07251091, -0.0801819 ],
        [-0.08669934, -0.00355349],
        [-0.04075354,  0.02745337]],

       [[-0.01961133, -0.12969351],
        [ 0.05313357, -0.03944592],
        [-0.00887044,  0.03538894],
        [-0.04746778,  0.0877666 ],
        [-0.0760282 ,  0.12020133]],

       [[-0.0397478 ,  0.0638587 ],
        [-0.06989139,  0.10420511],
        [-0.07821836, -0.07957634],
        [-0.07398938, -0.17622876],
        [-0.08042201, -0.10456244]]], dtype=float32)
