[View in Colaboratory](https://colab.research.google.com/github/bell-one/tf_colab/blob/master/SoftmaxClassification_tf.ipynb)

In [0]:
import tensorflow as tf

In [0]:
# initilize variables
x_data = [[1, 2, 1, 1,], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6,], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]
# declare tf variables
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
# training values
nb_classes = 3
W = tf.Variable(tf.random_normal([4, nb_classes]), name = 'w')
b = tf.Variable(tf.random_normal([nb_classes]), name='b')

In [0]:
# initilize hypo, cost, opti equation
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [11]:
# launch graph
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for step in range(2001):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0:
      print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
  all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4 , 3], [1, 1, 0, 1]]})
  print(all, sess.run(tf.argmax(all, 1)))

0 1.6902092
200 0.5700877
400 0.47208488
600 0.39465714
800 0.3220613
1000 0.25249815
1200 0.2254958
1400 0.20530406
1600 0.18830663
1800 0.17380841
2000 0.16130465
[[1.3046871e-02 9.8694593e-01 7.2242142e-06]
 [7.8728712e-01 2.0118745e-01 1.1525462e-02]
 [1.3837174e-08 3.4131296e-04 9.9965870e-01]] [1 0 2]
