[View in Colaboratory](https://colab.research.google.com/github/bell-one/tf_colab/blob/master/SoftmaxClassification_tf.ipynb)

In [0]:
import tensorflow as tf

In [0]:
# initilize variables
x_data = [[1, 2, 1, 1,], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6,], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]
# declare tf variables
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
# training values
nb_classes = 3
W = tf.Variable(tf.random_normal([4, nb_classes]), name = 'w')
b = tf.Variable(tf.random_normal([nb_classes]), name='b')

In [0]:
# initilize hypo, cost, opti equation
logits = tf.matmul(X,W)+b
hypothesis = tf.nn.softmax(logits)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [13]:
# launch graph
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for step in range(2001):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0:
      print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
  all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4 , 3], [1, 1, 0, 1]]})
  print(all, sess.run(tf.argmax(all, 1)))

0 4.6472774
200 0.62583137
400 0.5136163
600 0.4200943
800 0.32863665
1000 0.24460171
1200 0.21695884
1400 0.19778663
1600 0.18162124
1800 0.16781597
2000 0.15589736
[[2.2911292e-03 9.9769813e-01 1.0733069e-05]
 [9.1009998e-01 7.9223424e-02 1.0676648e-02]
 [1.8281119e-08 3.6129783e-04 9.9963868e-01]] [1 0 2]
